[package]
name = "day4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-backtrace = "0.5.1"
color-eyre = "0.6.2"
eyre = "0.6.8"
nom = "7.1.1"
